### ISSUE TITLE
multiple opened app-drawer may cause Maximum call stack size exceeded error

### ISSUE THREAD

**Issue by frankiefu** [PolymerLabs/app-layout#113]
- Run the jsbin: http://jsbin.com/mumagoquni/edit?html,output
- Resize the window so is in narrow mode.
- Click the left-arrow button to open the inner drawer.
- Then click the menu button to open the outer drawer.
- Now click on the input to focus it.
- You will see `Maximum call stack size exceeded` error in the console

**Comment by frankiefu** [comment]
The issue is both the outer and the inner drawers are competing to set focus on its `#containerConatiner`.  One way to fix this is to identify which app-drawer is the active one and only the active one should receive focus.

**Comment by keanulee** [comment]
@frankiefu I think we need to rethink overlays and perhaps fold this into `IronOverlayBehavior`

**Comment by frankiefu** [comment]
Yes, I agree it would be ideal to use `IronOverlayBehavior` for all the overlay stuffs.  Definitely it will be good to experiment using `IronOverlayBehavior` and see what do we need in order to use `IronOverlayBehavior`.  But I suspect the current `IronOverlayBehavior` is probably way too much for `app-drawer` and probably quite a bit of work will be needed, which may make sense for IronOverlayBehavior v2.  We probably need something simpler in `app-drawer` for now.
