### ISSUE TITLE
app-drawer - position-fixed limits drop in use cases

### ISSUE THREAD

**Issue by ktiedt** [PolymerLabs/app-layout#121]
- Allow for position other than fixed
- Animate width (maybe?) - to allow parent node to collapse around it.

What this allows for is 2 fold.
1. app-drawer can now be dropped into an existing nav container and expand/collapse that container
2. becomes a drop in replacement for non floating/blocking menus.

**Comment by ktiedt** [comment]
I think I have an alternative solution for this besides causing layout events due to the width changing. Should have a PR later today if it all works out.

**Comment by keanulee** [comment]
@ktiedt Did #132 help with this, or do you need more changes?

**Comment by ktiedt** [comment]
We are good, thank you!
