### ISSUE TITLE
Performance improvement for app-drawer

### ISSUE THREAD

**Issue by fleckdalm** [PolymerLabs/app-layout#127]
Adding this line of css:
`app-drawer #contentContainer{
    will-change: transform;
}` greatly improves the transition animation of the app drawer. Especially on older mobile devices there is notable difference.

**Comment by ebidel** [comment]
+1

**Comment by keanulee** [comment]
We already use the translate3d hack on `#contentContainer` to force a layer (including browsers that don't support will-change). Is this not working on a browser where will-change does?

**Comment by ebidel** [comment]
https://github.com/PolymerLabs/app-layout/blob/master/app-drawer/app-drawer.html#L139-L140 is the only place I see the `translateZ(0)`, but that's on the `#scrim`. I think @fleckdalm was suggesting
we need a `will-change` on `#contentContainer` because that's also doing a `transform3d`.

**Comment by keanulee** [comment]
`#contentContainer` already has a `transform: translate3d(-100%, 0, 0);` (https://github.com/PolymerLabs/app-layout/blob/master/app-drawer/app-drawer.html#L96) which seems to already force a layer.
