### ISSUE TITLE
Missing property declaration for app-header

### ISSUE THREAD

**Issue by Zecat** [PolymerLabs/app-layout#128]
Polylint failed for app-header
> Property isAttached not found in 'properties' for element 'app-header'

isAttached is used by [resetLayout()](https://github.com/PolymerLabs/app-layout/blob/master/app-header/app-header.html#L394) but undeclared

**Comment by blasten** [comment]
True, that is an issue in Polylint.

**Comment by frankiefu** [comment]
Since this is not an issue in app-layout, closing.
