### ISSUE TITLE
"wide" parameter in function ?

### ISSUE THREAD

**Issue by myuseringithub** [PolymerLabs/app-layout#133]
Hi, in pattern > transform navigation, there is a function "onLayoutChange" that accepts parameter "wide", and then checks if it is true. Where did this parameter come from and where is it defined ?
`
onLayoutChange: function(wide) { if (wide && drawer.opened) {
          ...
        }
      }
`
I'm trying to understand how it works, thanks.

**Comment by frankiefu** [comment]
`onLayoutChange` is the change handler for the `wideLayout` property.  And `wide` is the new value for the property: https://www.polymer-project.org/1.0/docs/devguide/properties.html#change-callbacks
