### ISSUE TITLE
Pesto template spams the history, navigating between / and /#home

### ISSUE THREAD

**Issue by tjsavage** [PolymerLabs/app-layout#134]
Repro:

Navigate to http://polymerlabs.github.io/app-layout/templates/pesto/
Hit the back button
Note that the back button history is spammed with the url.

**Comment by abdonrd** [comment]
I can reproduce too with Chrome v49 and FF v45.

**Comment by frankiefu** [comment]
FYI, @keanulee verified that this will be fixed once we switch to "soon to be made public" carbon-route.

**Comment by keanulee** [comment]
This should be fixed now.
