### ISSUE TITLE
Drawer swipe

### ISSUE THREAD

**Issue by aydun1** [PolymerLabs/app-layout#14]
I find this to be much faster than the standard layout on browsers other than Chrome (where Chrome seems to perform just as well on both), however I miss being able to swipe in the side drawer.

Is this a feature that's likely to be implemented? I notice on the Polymer docs site that you can swipe to close the drawer, but not open.

Is this a feature that you're likely to implement?

Thanks!

**Comment by frankiefu** [comment]
Yes.  We will implement the swipe drawer feature.

**Comment by keanulee** [comment]
This has been implemented.

**Comment by myuseringithub** [comment]
Yay ! I'm so excited. Thank you
