### ISSUE TITLE
app-drawer-layout content not resizing in IE

### ISSUE THREAD

**Issue by moduv5** [PolymerLabs/app-layout#144]
Hi,
When using an app-drawer inside an app-drawer-layout and we resize the page to make app-drawer disappear, the app-header is not resizing well. 
Step to reproduce:
1)	Go in demo5.html in IE (I used IE 11 for my test)
2)	Click on explorer box to reduce windows size (The bug only appear in a one shot resize, not when resizing windows by the corner).  The internet explorer window should be at a point that make the drawer disappear after clicking the resize button.
3)	We can see that the app-header doesn’t fill the remaining space of the drawer.

Screen shot: 

 
![image](https://cloud.githubusercontent.com/assets/6440586/14094769/6530f93a-f527-11e5-91c9-0f3a2a45de41.png)

Note: I do not only see this bug in app-header. In my app, I have an element that use iron-resize to take the width of the app-header-layout inside the app-drawer-layout and I got the same problem. It seems that the iron-resize event is trigger before the app-drawer have disappear.

**Comment by frankiefu** [comment]
This is similar to toggling `forceNarrow` which causes `_responsiveChange` and then `resetLayout` to be called.  Currently in `app-drawer-layout.resetLayout` we don't notify elements inside that the layout has changed.  I think we should investigate making app-drawer-layout a `IronResizableBehavior`.  This way it can notify other elements that the layout/size has changed.
