### ISSUE TITLE
Allow app-header to not be a direct children of app-header-layout

### ISSUE THREAD

**Issue by moduv5** [PolymerLabs/app-layout#147]
Hi,

I want to put my app-header in a polymer elements to use it across my application. However there are some functionality that doesn't work when doing that. For example, if i put the fixed attribute on the app-header, the header doesn't stay fixed in the page.

**Comment by blasten** [comment]
did you set `position:fixed` on the app-header?

**Comment by moduv5** [comment]
I tried this, but my when doing that, my content is displayed over my toolbar. I tried to set a z-index on my app-header but now its the drawer that is displayed behind my toolbar. 

I think that the fixed attribute should work even if the app-header is not a direct descendant of app-header-layout. The others attributes that i use seems to work.

**Comment by keanulee** [comment]
If you're using `app-header-layout`. `app-header` needs to be its immediate child. `app-header-layout` basically just offsets the content so that it's not under the header, so if you can't accommodate that requirement you could just offset the content yourself.

**Comment by moduv5** [comment]
I was thinking that the app-header-layout should not be that restrictive and instead of needing the app-header element for its header part, it could use a class as selector. Something like .app-header should do the tricks?

If I take paper-header-panel for example, it allows paper-toolbar or .paper-header as header
`<content id="headerContent" select="paper-toolbar, .paper-header"></content>`

What do you think of that?

**Comment by keanulee** [comment]
`app-*-layout` elements are designed to be simple helpers for using `app-drawer` and `app-header`. It does not support non-`app-header` elements. For a the use case you're describing, it's probably better to just style the header (with `position: fixed: top: ...`) and offset the content (`margin-top: ...`) yourself.
