### ISSUE TITLE
FF problem with URL encoding in Shrine template

### ISSUE THREAD

**Issue by atomikolex** [PolymerLabs/app-layout#159]
### Description
It seems that Firefox and Chrome handle non-Ascii URLs differently. This can lead to problems when you connect the URL to your app with carbon-location. 

### Steps to reproduce
1. Clone app-layout and open shrine-app.html in Shrine template. 
2. Change the values in the section array to unsafe ASCII or non ASCII characters  'About me' and 'België', and the corresponding values in the last ("category") keys of each object in the featured.json array.
3. Open in Firefox and Chrome. > Works in Chrome, but not in Firefox.
4. Then set the values in the section array and in featured.json to URL encoded values 'About+me' and 'Belgi%C3%AB', and open in Firefox and Chrome. > Will work in both, but undesirable.

### Problem
It seems that in case of non-ASCII URLs the data object exposed by carbon-route is URL encoded in Firefox and so a filter function [as used in the Shrine template](https://github.com/PolymerLabs/app-layout/blob/master/templates/shrine/src/shrine-app.html#L363-367) has no passing items.
Should this be handled on app level or rather be taken care of by carbon-route and carbon-location?

### Affected Browsers
- [x] Firefox (45)
- [ ] Chrome
- maybe more, didn't check

**Comment by keanulee** [comment]
Closing - see https://github.com/PolymerLabs/app-layout/pull/160#issuecomment-209130416
