### ISSUE TITLE
Consider alternate API for scroll effects

### ISSUE THREAD

**Issue by arthurevans** [PolymerLabs/app-layout#161]
Generally we've discouraged people from adding things to the `Polymer` namespace (for example, behaviors, where we suggest people create their own namespace).

The current scroll effects API requires people to attach their effects to the `Polymer.AppLayout.scrollEffects` namespace. I wonder if it would make sense to have some kind of registration mechanism instead.

**Comment by frankiefu** [comment]
I like the suggestion.  Maybe something like this:

```
Polymer.AppLayout.registerEffect('my-effect', {
  setUp: function(config) {
    // the effect's config is passed to the setUp.
  },

  run: function(progress) {
     // the progress of the effect
  },

  tearDown: function() {
     // clean up and reset of states
  }
});
```

@blasten WDYT?

**Comment by blasten** [comment]
I like it :)

**Comment by frankiefu** [comment]
Fixed in https://github.com/PolymerLabs/app-layout/pull/171
