### ISSUE TITLE
Increase drawer swipe sensitivity.

### ISSUE THREAD

**Issue by myuseringithub** [PolymerLabs/app-layout#165]
App-drawer swipe to open is not as responsive as paper elements counterpart. On the example demos provided, trying to rapidly swipe on mobile doesn't work or using thumb with slight touch doesn't open the drawer either. 
I'm sure it should be a quick issue to improve.

**Comment by frankiefu** [comment]
In `app-drawer` we set the edge width to `15px`.  `paper-drawer-panel` uses `30px` as the default.  I think we should use the same as in Android native navigation drawer which I think is `20px` but we should confirm.
