### ISSUE TITLE
wheel scroll on paper-dialog now propagates to app-layout

### ISSUE THREAD

**Issue by kenchris** [PolymerLabs/app-layout#168]
This was not the case with paper-toolbar and friends.

In my example, I have a fullscreen dialog (width: 100vw, height: 100vh) and then scrolling to the bottom, the dialog itself scrolls away.

**Comment by kenchris** [comment]
https://jsbin.com/qemilas/3/edit?html,output

**Comment by motss** [comment]
@kenchris How about listening to `iron-overlay-opened` and disable the document scrolling while restore the document scrolling by listening to `iron-overlay-closed`.

I basically do this on all dialogs.

At `paper-dialog`,
```
<paper-dialog on-iron-overlay-opened="_disableDocumentScrolling" on-iron-overlay-closed="_restoreDocumentScrolling"></paper-dialog>
```

To disable document scrollling on dialog opened,
```
'_disableDocumentScrolling': function() {
  document.body.style.overflow = 'hidden';
}
```

To restore document scrolling on dialog closed,
```
'_restoreDocumentScrolling': function() {
  document.body.style.overflow = '';
}
```

**Comment by blasten** [comment]
I think @motss's solution should help you.

**Comment by kenchris** [comment]
Isn't that a very ugly work around? Wouldn't the common case be that you don't want the scrolling to affect the parent (as that is the common case in most native apps etc)

**Comment by kenchris** [comment]
Wouldn't it be better if the dialog by default didn't propagate its events then?

I find it counter intuitive, you scroll something and then when you reach the end (or beginning), you scroll something behind and most likely lose your position and get confused. 

That is not user friendly and it's different that native platforms. (I am sure material design guidelines have something to say on that :-))

**Comment by kenchris** [comment]
@rickbyers is there a nicer way to do this? ie blocking events to parent, insteads of turning scroll off for the body?

**Comment by blasten** [comment]
@kenchris You can also use `Polymer.IronDropdownScrollManager`. https://github.com/PolymerElements/iron-dropdown/blob/master/iron-dropdown-scroll-manager.html. For example:

```js
'_disableDocumentScrolling': function(e) {
  Polymer.IronDropdownScrollManager.pushScrollLock(e.target);
},
'_restoreDocumentScrolling': function(e) {
  Polymer.IronDropdownScrollManager.removeScrollLock(e.target);
}
```

There's also a feature requests in https://github.com/PolymerElements/iron-overlay-behavior/issues/140

**Comment by RByers** [comment]
This is actually a bit of a whole in the web platform IMHO, see [chromium bug 162179](http://crbug.com/162179).  It's not currently possible to prevent scrolls over one element from propagating up to the viewport.  People play tricks like consuming wheel events, but that doesn't work for touch.  This is much less annoying in browsers that have scroll latching (scroll target never changes within a given gesture) - Safari, Chrome (touch only, soon also wheel), and opt-in in Edge with -ms-scroll-chaining:none.  I appreciate any suggestions you have on how the web platform should be extended to fix this (we could just add a CSS property or something).
