### ISSUE TITLE
Compiler errors - ElementWithBackground

### ISSUE THREAD

**Issue by ktiedt** [PolymerLabs/app-layout#174]
With the changes to app-scroll-effects, these compiler errors now get thrown

```
 ERROR - Bad type annotation. Unknown type Polymer.AppLayout.ElementWithBackground
    /** @this Polymer.AppLayout.ElementWithBackground */
```

One for each effect type.

**Comment by frankiefu** [comment]
This [PR](https://github.com/PolymerLabs/polymer-externs/pull/63) should fix the issue.

**Comment by frankiefu** [comment]
Fixed by https://github.com/PolymerLabs/polymer-externs/pull/63
