### ISSUE TITLE
pesto doesn't the recipes anymore

### ISSUE THREAD

**Issue by blasten** [PolymerLabs/app-layout#177]
http://polymerlabs.github.io/app-layout/templates/pesto/#/home

<img width="865" alt="screen shot 2016-04-15 at 7 07 05 pm" src="https://cloud.githubusercontent.com/assets/1410613/14578448/46143656-033d-11e6-9093-0bb3445241dc.png">

**Comment by jparish3** [comment]
ZUPERKULBLOG does not load content from articles.json. related to carbon-routing?

**Comment by keanulee** [comment]
Ahh, forgot to update the data with the recent publish. Fixed now (https://github.com/PolymerLabs/app-layout/commit/9ae8a6a3d2967c140994850c3e04081fbdf949f8)
