### ISSUE TITLE
Various demos on https://polymerlabs.github.io/app-layout/docs.html are broken

### ISSUE THREAD

**Issue by Analect** [PolymerLabs/app-layout#184]
While the docs button works ... the demo one doesn't for more most of this suite of elements.  Would be great to get this working.

**Comment by blasten** [comment]
This issue should be fixed in master, but it seems like some weird caching policy going on `view-source:http://cdn.rawgit.com/polymerlabs/app-layout/master/app-drawer-layout/app-drawer-layout.html` because they are still broken. @frankiefu ?

**Comment by frankiefu** [comment]
It seems like `iron-component-page` is doing url rewrite: https://github.com/PolymerElements/iron-component-page/blob/master/iron-component-page.html#L528

**Comment by frankiefu** [comment]
Found the github issue: https://github.com/PolymerElements/iron-component-page/issues/44
