### ISSUE TITLE
app-header-layout doesn't re-evaluate when CSS changes app-header height.

### ISSUE THREAD

**Issue by myuseringithub** [PolymerLabs/app-layout#186]
When CSS changes (without resizing window) the height of app-toolbar (to a smaller height as an example), a gap is created between content and app-toolbar.
If window is resized the contentContainer of app-header-layout refreshes its height and gap disappears.

How can I cause the app-header-layout to observe CSS changes or refresh when styles of children (i.e. app-header or app-toolbar) are changed ?

![gap app-header-layout](https://cloud.githubusercontent.com/assets/7758497/14881577/3c41f866-0d3d-11e6-9086-def3c245da22.PNG)

Thanks

**Comment by myuseringithub** [comment]
![gap app-header-layout](https://cloud.githubusercontent.com/assets/7758497/14881563/2e8bb018-0d3d-11e6-9e77-301179d90469.PNG)

**Comment by myuseringithub** [comment]
padding-top of <div id="contentContainer"> should be recalculated. I'm not sure how Shrine template example achieve this. Trying to check the code but cannot seem to figure it out.

**Comment by myuseringithub** [comment]
So it uses this function: 
`
    _hashDidChange: function() {
      this.$.header._scrollTop = 0;
      this.$.header.resetLayout();
      this.$.drawer.close();
    },
`

**Comment by frankiefu** [comment]
There isn't a good way to observe CSS changes.  I'd suggest to call `this.$.header.resetLayout()` manually after changes that affect the height of the header.
