### ISSUE TITLE
Cannot give outside element as scrollTarget

### ISSUE THREAD

**Issue by vimalraj-a** [PolymerLabs/app-layout#188]
I am trying to point child element of app-header as scroll target something similar to paper-header-panel with waterfall effect.

```
<app-header-layout>
    <app-drawer-layout id="drawerLayout">
      <app-drawer>
        <div class="drawer-content">
          <app-menu class="customScroller y" selected="{{menu.selected}}"></app-menu>
        </div>
      </app-drawer>
      <div id="content" style="min-height: 600px;"></div>
    </app-drawer-layout >
</app-header-layout>
```
then 

```
attached(){
this.$.appHeader.scrollTarget = this.$.content;
}
```

**Comment by blasten** [comment]
> child element of app-header as scroll target

Did you mean a parent element? Where is the app-header?

**Comment by vimalraj-a** [comment]
small correction in my first comment. I was trying to point outside element of app-header as scroll target and app-header is the child element of app-header-layout. forgot to mention in the snippet. here is full code

```
<app-header-layout>
    <app-drawer-layout id="drawerLayout">
      <app-drawer>
        <div class="drawer-content">
          <app-menu class="customScroller y" selected="{{menu.selected}}"></app-menu>
        </div>
      </app-drawer>
      <div id="content" style="min-height: 600px;"></div>
    </app-drawer-layout >
    <app-header id="appHeader">
       <app-toolbar>
          <div title> App Title</div>
       </app-toolbar>
    </app-header>
</app-header-layout>
```

**Comment by keanulee** [comment]
`<app-header-layout>` will internally put a `div#contentContainer` wrapper element around all non-`<app-header>` children and will either set `div#contentContainer` (when `hasScrollingRegion` is enabled) or the document scroller as the scroll target, so you shouldn't have to set it yourself. If you want the waterfall effect, set the waterfall effect on `<app-header>` (e.g. https://github.com/PolymerLabs/app-layout/blob/master/demo/demo2.html#L62)

**Comment by vimalraj-a** [comment]
waterfall effect is not working when `div#contentContainer` or if I set `scrollingTarget `manually. here is the jsbin link http://jsbin.com/zegewidoqe/edit?html,output

**Comment by keanulee** [comment]
What are you trying to accomplish (waterfall header inside a drawer?)? `scrollTarget` is an HTMLElement, not a string that references an element.

```
drawer.scrollTarget = document.querySelector('div');
```

**Comment by vimalraj-a** [comment]
I have assigned `div#content` as `scrollTarget` of `app-header` element. But, `div#content` is not scrollable. That's the reason I can't get waterfall effect while scrolling.


```
this.$.appHeader.scrollTarget = this.$.drawerLayout;
```
This works for me

here is the working jsbin link(http://jsbin.com/nogapi/1/edit?html,js), output(http://output.jsbin.com/nogapi)
