### ISSUE TITLE
Test drive drawer not opening on mobile emulation

### ISSUE THREAD

**Issue by tjsavage** [PolymerLabs/app-layout#190]
When I load testdrive on Chrome in mobile emulation mode, I cannot open the drawer using the hamburger menu. I imagine this will be a common way for people to check out the different animations.

**Comment by frankiefu** [comment]
I can't seem to reproduce the problem on Chrome.  I did occasionally observe weird things happening when switching to mobile emulation mode.  Usually when that happens I open another browser tab and try again.

**Comment by tjsavage** [comment]
Yeah shoot can't repro either now. Apologies for the fire drill.
