### ISSUE TITLE
The app-drawer to slide out with a slide gesture?

### ISSUE THREAD

**Issue by mercmobily** [PolymerLabs/app-layout#192]
With `paper-drawer-panel`, we got "for free" the feature where you could slide the panel out easily.
Is anything like this available with `app-drawer`? I looked and looked -- while it does slide back in with a gesture, it won't slide out like `paper-drawer-panel` was.

Please go ahead and embarrass me, pointing out something totally obvious that shows that I am blind...!

**Comment by frankiefu** [comment]
Set `swipeOpen` property on the `app-drawer`, e.g.
```
<app-drawer swipe-open>
```

**Comment by mercmobily** [comment]
I don't believe this. Not again.
(Thank you Frankie!)
