### ISSUE TITLE
provide build information

### ISSUE THREAD

**Issue by ilikerobots** [PolymerLabs/app-layout#198]
Is there a build script available?  I'm trying to test my changes against the build output generated for gh-pages, but I'm not sure exactly how the gh-pages branch is built.

**Comment by keanulee** [comment]
The gh-pages branch has vulcanized versions of each page/demo (e.g. view-source:http://polymerlabs.github.io/app-layout/). You can make the index page by doing:

```bash
vulcanize --inline-css --inline-scripts index.html
```
