### ISSUE TITLE
threadhold -> threshold

### ISSUE THREAD

**Issue by robdodson** [PolymerLabs/app-layout#2]
I think the intention here was to use the word threshold? https://github.com/PolymerLabs/app-layout/blob/master/x-header/x-header.html#L81-L89

**Comment by addyosmani** [comment]
:+1: for threshold.

**Comment by frankiefu** [comment]
fixed by https://github.com/PolymerLabs/app-layout/commit/5457545a26a373fc6cc32bc0dd934f8826eb6601#diff-4205f47e0a8c34f82f5a8b0abb242603
