### ISSUE TITLE
main content is scrolled behind the drawer and scrim

### ISSUE THREAD

**Issue by frankiefu** [PolymerLabs/app-layout#21]
To reproduce:
- open `app-layout/demo/demo2.html` on mobile, e.g iPhone
- try to touch scroll on the drawer

Observed:
the main content behind the scrim scroll.

Expected:
the main content behind the scrim should not scroll.

We used to have code in `DocumentScrollBehavior` to help decide `shouldEnableDocScroll`.  The code is problematic and we commented that out.  We need to find another solution to solve this.

**Comment by frankiefu** [comment]
@blasten Can you take a look to see if there is a better way to solve this issue?

**Comment by blasten** [comment]
@frankiefu  I will
