### ISSUE TITLE
'reveals' problem in iPhone and iPad

### ISSUE THREAD

**Issue by diegohaz** [PolymerLabs/app-layout#36]
Probably because of how the scroll works on these devices, `<app-header reveals>` seems weird. It doesn't reveals while scrolling, but only when scroll stops, causing the toolbar's position to flash.

Is this a known issue? Is there any solution?

**Comment by diegohaz** [comment]
Well, I found out that this is actually a problem with Chrome for iOS. On Safari, it works fine.

**Comment by blasten** [comment]
@diegohaz That sounds plausible. Chrome for iOS uses Apple's `UIWebView`, which still runs a pretty old version of webkit. This version has this scroll event issue; however, Mobile Safari uses a version in which this issue is fixed.
