### ISSUE TITLE
After recent update, "Uncaught TypeError: Cannot set property 'opened' of undefined".

### ISSUE THREAD

**Issue by myuseringithub** [PolymerLabs/app-layout#50]
Getting errors in console, and the drawer doesn't appear at all, neither does the related hamburger button: 
`Uncaught TypeError: Cannot set property 'opened' of undefined`
`(anonymous function)	@ app-drawer-layout.html:188`
`Debouncer.complete	@ polymer-mini.html:2097`
`boundComplete	@ polymer-mini.html:2076`
`Polymer.Async._atEndOfMicrotask		@ polymer-mini.html:2053`
`window.MutationObserver.observe.characterData		@ polymer-mini.html:2068`

The anonymous function points to: 
`resetLayout: function() {`
`....`
->   ` this.drawer.opened = !this.narrow;`
`....`

![err1](https://cloud.githubusercontent.com/assets/7758497/12805911/51112828-cb09-11e5-98a7-4a1ba47bb998.PNG)
![err2](https://cloud.githubusercontent.com/assets/7758497/12805910/510feb34-cb09-11e5-81c4-1a829e823722.PNG)

**Comment by motss** [comment]
:+1:

**Comment by jcpilario** [comment]
seems you need to specifically use app-drawer element now on your app-drawer-layout

**Comment by motss** [comment]
@jcpilario You're right. Now no more specifying attribute `drawer` and `main`.

**Comment by motss** [comment]
It works and use `swipe-open` attribute on `app-drawer` to enable swiping which is not the default.

**Comment by myuseringithub** [comment]
Okay, now its working. After I checked out the demos of app-drawer & app-drawer-layout, and applied the changes. 
Also the previously "drawer-width" property that was applied to app-drawer-layout was removed. So now the way to change the width of drawer is as follows: 
app-drawer {
    --app-drawer-content-container: {
         width: 320px;
    }
}

Everything works as expected. Thanks for your amazing work.

**Comment by frankiefu** [comment]
Sorry about the breaking changes.  Yes we are still at `pre-release` and likely we are going to make changes that will break stuffs.  We will try to see if we can put the breaking changes in the pre-release note next time.

**Comment by Vietworm** [comment]
Mmm .. I have the same issue, using `app-drawer-layout` 

```diff
-Uncaught TypeError: Cannot set property 'opened' of undefined
+   (anonymous function)	@	app-drawer-layout.html:188
```

@myuseringithub , please expect your solved. Thanks!
