### ISSUE TITLE
Make templates/publishing more reusable

### ISSUE THREAD

**Issue by addyosmani** [PolymerLabs/app-layout#54]
I've previously talked to @justinfagnani about what we can do to make the publishing template more reusable out of the box :runner:. 

Could we look at making the data for the below less coupled to the current implementation?

- Inline categories: https://github.com/PolymerLabs/app-layout/blob/master/templates/publishing/src/blog-app.html#L252
- Inline reference to film categories: https://github.com/PolymerLabs/app-layout/blob/master/templates/publishing/src/blog-app.html#L245 and https://github.com/PolymerLabs/app-layout/blob/master/templates/publishing/src/blog-app.html#L231
- Use of static category reference: https://github.com/PolymerLabs/app-layout/blob/master/templates/publishing/src/blog-app.html#L225
- nav-menu includes an inline list of menu items that could be pulled from some external data source instead https://github.com/PolymerLabs/app-layout/blob/master/templates/publishing/src/blog-app.html#L183

We already use an external JSON file for [articles](https://github.com/PolymerLabs/app-layout/blob/master/templates/publishing/data/articles.json) so maybe something similar for the rest of the app?

cc @robdodson who did https://github.com/PolymerLabs/zuperkulblog-progressive in case he has other thoughts here.

**Comment by robdodson** [comment]
Yeah my biggest gotcha was that the template loaded all the article data up front, but that's probably not practical for a large app. I did a variation at https://github.com/polymerlabs/zuperkulblog-progressive which loads each section and articles as its own json file
