### ISSUE TITLE
More Behaviours too hook into and allow custom elements

### ISSUE THREAD

**Issue by kristianmandrup** [PolymerLabs/app-layout#8]
Since Polymer no longer supports inheritance, may I humbly suggest leveraging Behaviors much more!

Please see: https://github.com/PolymerElements/paper-scroll-header-panel/issues/50#issuecomment-144129056

I felt completely trapped when I tried to compose my main layout from smaller blocks since they were all seemingly hardcoded to use specific elements, parent/child relationships and selectors.

Along the same lines, I'd also suggest using shared styles much more for the same reasons, to empower the developer to combine and compose as needed!

**Comment by blasten** [comment]
Do you have a specific example using app-layout?

**Comment by frankiefu** [comment]
Since there is no responses to the question, closing it.
