### ISSUE TITLE
Remove dependency on iron-list#custom-scroller

### ISSUE THREAD

**Issue by keanulee** [PolymerLabs/app-layout#80]
Right now app-layout's bower.json relies on iron-list#custom-scroller, which has not been merged to master (https://github.com/PolymerElements/iron-list/pull/85). We should remove this specific dependency.

**Comment by frankiefu** [comment]
This issues depends on https://github.com/PolymerLabs/app-layout/issues/46

**Comment by blasten** [comment]
fixed in master
