### ISSUE TITLE
Should this be possible?

### ISSUE THREAD

**Issue by RobMaskell** [PolymerLabs/app-layout#91]
I tried with the help of an app-header-layout, an app-header and a couple of app-toolbars to do the following but I couldn't get it to work, should the following be possible?

- top fixed height toolbar
- bottom toolbar that starts off a certain size and then condenses to a smaller size on scroll

I could get the two toolbars, and the condense to smaller size but the top toolbar always scrolled off screen which is the one I wanted to stay put.

Thanks in advance

**Comment by blasten** [comment]
You could do this:
```html
<app-header>
  <div primary>
    <app-toolbar>top bar</app-toolbar>
   <app-toolbar> fixed bottom bar</app-toolbar>
  </div>
   <app-toolbar>floating bottom bar</app-toolbar>
</app-header>
```

**Comment by frankiefu** [comment]
Closing it.  Please let us know if this is still an issue.

**Comment by RobMaskell** [comment]
I tried the solution suggested but it didn't seem to work, top bar was not fixed but the bottom was. I might have found a solution but I couldn't make it work with just the app-layout elements. If I get something working I'll post what I have for anyone else that hits this.
